hotelpartner/urls.py
from django.contrib import admin
from django.urls import path
from hotelpartner import views
app_name="hotelpartner"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("newhotelchain", views.create_hotel_chain, name="newhotelchain"),
    path("detailhotelchain/<int:pk>-<slug>.html", views.detailhotelchain, name="detailhotelchain"),
    path("detailhotelchain/<int:pk>-<slug>/edit", views.edithotelchain, name="edithotelchain"),
    path("deletehotelchain", views.delete_hotel_chain, name="deletehotelchain"),
    path("hotelchains", views.list_hotel_chain, name="listhotelchains")
]

project_hotel/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('hotelpartner/', include('hotelpartner.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('hotelpartner/', include('hotelpartner.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

templates/hotelchain/detailhotelchain.html
{% extends "base.html" %}

{% block content %}

detial hotel chain

    <label> title: </label> <span>{{ detail_hotel_chain.name }}</span>
    <br/>
    <label>state:</label><span>{{ detail_hotel_chain.state }}</span>
{% endblock %}

templates/hotelchain/hotelchain_create.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">

        {% csrf_token %}
        {{ hotel_chain_form.as_p}}
    <button type="submit">save</button>
    </form>
{% endblock %}

templates/hotelchain/hotelchain_edit.html
{% extends "base.html" %}

{% block content %}
    edit hotel chain 111
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
    <button type="submit">save</button>
    </form>
{% endblock %}

templates/hotelchain/hotelchains.html
{% extends "base.html" %}
{% block content %}
    <div>
    <h3>list hotels chain</h3>
    <br>
    <a href="{% url 'hotelpartner:newhotelchain' %}">Create new hotel chain</a>
    <br>

{% for hotel_chain in page_hotel_chains %}
{#    <label>name:</label> <a href="{% url 'hotelpartner:detailhotelchain' pk=hotel_chain.id %}">{{ hotel_chain.name }}</a>#}
    <br/>
    <label>name:</label> <a href="{{ hotel_chain.get_absolute_url }}">{{ hotel_chain.name }} solution 2</a>

    <br/>
    <label>state:</label> {{ hotel_chain.state }}
    <br/>
    <label>order:</label> {{ hotel_chain.order }}
    <br>

    <a href="javascript:void;" onclick="submitForm({{ hotel_chain.id }})">delete</a>
    <br>
    ===========
    <br/>
    {% endfor %}

    </div>
<div class="pagination">
    <span class="step-links">
        {% if page_hotel_chains.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_hotel_chains.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_hotel_chains.number }} of {{ page_hotel_chains.paginator.num_pages }}.
        </span>

        {% if page_hotel_chains.has_next %}
            <a href="?page={{ page_hotel_chains.next_page_number }}">next</a>
            <a href="?page={{ page_hotel_chains.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

    <form method="POST" id="delete-hotel-chain" action="{% url 'hotelpartner:deletehotelchain' %}">
    <input type="text" id="pk" name="pk" value="">
{% csrf_token %}
    </form>
    <script type="text/javascript">
    function submitForm(pk)
    {
        document.getElementById("pk").value = pk;
         document.getElementById("delete-hotel-chain").submit();
    }

    </script>

{% endblock %}