hotelpartner/urls.py
from django.contrib import admin
from django.urls import path
from hotelpartner import views
app_name="hotelpartner"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("login", views.login_request, name="login"),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("newhotelchain", views.create_hotel_chain, name="newhotelchain"),
    path("detailhotelchain/<int:pk>-<slug>.html", views.detailhotelchain, name="detailhotelchain"),
    path("detailhotelchain/<int:pk>-<slug>/edit", views.edithotelchain, name="edithotelchain"),
    path("deletehotelchain", views.delete_hotel_chain, name="deletehotelchain"),
    path("hotelchains", views.list_hotel_chain, name="listhotelchains")
]

project_hotel/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('hotelpartner/', include('hotelpartner.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('hotelpartner/', include('hotelpartner.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<menu>
    <ul>
        <li>home</li>
        <li>login</li>
        <li>logout</li>
        <li><a href="">list hotels chain</a></li>
        <li><a href="{%  url 'hotelpartner:listhotelchains' %}">list hotels chain</a></li>
        <li>about</li>
    </ul>
</menu>
{% block content %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
<div>
    <ul>
        <li><a href="newhotelchain">newhotelchain</a></li>
        <li></li>
    </ul>
    Home page
</div>
<div>
    {% if user.is_authenticated %}
    Wellcome, {{ user.get_username }}
    <a href="logout">Logout</a>
    {% else %}
    <a href="login" >Login di</a>
    {% endif %}

</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
    {{ login_form }}
    <br/>
        <br/>
    {% csrf_token %}
{#    <label>username:</label>#}
{#    <input id="username" type="text" name="username1" />#}
{#<label>password:</label>#}
{#    <input id="password" type="password" name="password1" />#}


    <button type="submit" > Login</button>
    </form>

{% endblock %}

templates/menu.html
{% extends 'base.html' %}
{% block menu %}
<menu>
    <ul>
        <li>home</li>
        <li>login</li>
        <li>logout</li>
        <li><a href="">list hotels chain</a></li>
        <li><a href="{%  url 'hotelpartner:hotelchains' %}">list hotels chain</a></li>
        <li>about</li>
    </ul>
</menu>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
    <form  method="POST">
    {% csrf_token %}
        {{ form }}
        <button type="submit">register</button>
    </form>


{% endblock %}